jekyll: update to valid markdown tool
Fixes:

    Markdown processor: "redcarpet" is not a valid Markdown processor.
                        Available processors are: kramdown

      Conversion error: Jekyll::Converters::Markdown encountered an error while converting '_posts/2013-08-17-hello-world.md':
                        Invalid Markdown processor given: redcarpet
                 ERROR: YOUR SITE COULD NOT BE BUILT:
                        ------------------------------------
                        Invalid Markdown processor given: redcarpet
                        ------------------------------------------------
          Jekyll 4.3.1   Please append `--trace` to the `build` command
                         for any additional information or backtrace.
                        ------------------------------------------------

Signed-off-by: Robbie Harwood <rharwood@pm.me>